# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-the-Chrome-addon-in-the-headless-mode
dist: trusty
# this will install chrome
addons:
  chrome: stable

language: node_js
node_js:
  - 8
